all:
  hosts:
    sdwan_manager:
      ansible_host: 198.18.1.10
      ansible_connection: local
  vars:
    vmanage_host: 198.18.1.10
    vmanage_port: 443
    vmanage_username: admin
    vmanage_password: admin
    validate_certs: no
